// //GET_POST_PUT_DELETE

// //GET ALL POSTS BY ID
// export const GET_POSTS_REQUEST = "GET_POSTS_REQUEST"
// export const GET_POSTS_RECEIVE = "GET_POSTS_RECEIVE"
// export const GET_POSTS_FAILURE = "GET_POSTS_FAILURE"

// //GET POST BY ID
// export const GET_POST_REQUEST = "GET_POST_REQUEST"
// export const GET_POST_RECEIVE = "GET_POST_RECEIVE"
// export const GET_POST_FAILURE = "GET_POST_FAILURE"

// // UPDATE POST (PUT REQUEST)
// export const UPDATE_POST_REQUEST = "UPDATE_POST_REQUEST"
// export const UPDATE_POST_RECEIVE = "UPDATE_POST_RECEIVE"
// export const UPDATE_POST_FAILURE = "UPDATE_POST_FAIURE"

// // CREATE POST (POST REQUEST)
// export const CREATE_POST_REQUEST = "CREATE_POST_REQUEST"
// export const CREATE_POST_RECEIVE = "CREATE_POST_RECEIVE"
// export const CREATE_POST_FAILURE = "CREATE_POST_FAILURE"

// // DELETE POST (DELETE REQUEST)
// export const DELETE_POST_REQUEST = "DELETE_POST_REQUEST"
// export const DELETE_POST_RECEIVE = "DELETE_POST_RECEIVE"
// export const DELETE_POST_FAILURE = "DELETE_POST_FAILURE"

const GET_POSTS = {
    REQUEST: 'GET_POSTS_REQUEST',
    RECEIVE: 'GET_POSTS_RECEIVE',
    FAILURE: 'GET_POSTS_FAILURE'
  }
  
  const GET_POST = {
    REQUEST: 'GET_POST_REQUEST',
    RECEIVE: 'GET_POST_RECEIVE',
    FAILURE: 'GET_POST_FAILURE'
  }
  
  const UPDATE_POST = {
    REQUEST: 'UPDATE_POST_REQUEST',
    RECEIVE: 'UPDATE_POST_RECEIVE',
    FAILURE: 'UPDATE_POST_FAILURE'
  }
  
  const CREATE_POST = {
    REQUEST: 'CREATE_POST_REQUEST',
    RECEIVE: 'CREATE_POST_RECEIVE',
    FAILURE: 'CREATE_POST_FAILURE'
  }
  
  const DELETE_POST = {
    REQUEST: 'DELETE_POST_REQUEST',
    RECEIVE: 'DELETE_POST_RECEIVE',
    FAILURE: 'DELETE_POST_FAILURE'
  }

const CLEAR_LIST = "CLEAR_LIST"
const CLEAR_DATA = "CLEAR_DATA"

  export {
    GET_POST,
    GET_POSTS,
    DELETE_POST,
    CREATE_POST,
    UPDATE_POST,
    CLEAR_LIST,
    CLEAR_DATA
  }

